name       : python-trio-websocket
version    : 0.10.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/t/trio-websocket/trio-websocket-0.10.3.tar.gz : 1a748604ad906a7dcab9a43c6eb5681e37de4793ba0847ef0bc9486933ed027b
license    : MIT
component  : programming.python
summary    : WebSocket client and server implementation for Python Trio
description: |
    This library implements both server and client aspects of the the WebSocket protocol, striving for safety, correctness, and ergonomics. It is based on the wsproto project, which is a Sans-IO state machine that implements the majority of the WebSocket protocol, including framing, codecs, and events. This library handles I/O using the Trio framework.
builddeps  :
    - python-build
    - python-exceptiongroup
    - python-installer
    - python-packaging
    - python-trio
    - python-wheel
    - python-wsproto
rundeps    :
    - python-exceptiongroup
    - python-trio
    - python-wsproto
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
